import type { NextPage } from "next";
import Head from "next/head";
import { commerce } from "lib/commerce";
import { useQuery } from "react-query";
import { useEffect } from "react";
import ProductsGrid from "components/ProductsGrid";
import Navigation from "components/navigation";

const Home: NextPage = () => {
  const { data, isLoading } = useQuery(["products"], async () =>
    commerce.products.list()
  );
  useEffect(() => {
    console.debug(data);
  }, [data]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className="container">
        <h1 className="text-center">My Shop</h1>

        {isLoading ? (
          <p>loading</p>
        ) : (
          <ProductsGrid products={data?.data || []} />
        )}
      </main>
    </div>
  );
};

export default Home;
