import { Counter } from "components/Counter";
import type { NextPage } from "next";
import Head from "next/head";
import { commerce } from "lib/commerce";
import { useQuery } from "react-query";
import { useEffect } from "react";
import Image from "next/image";

const Home: NextPage = () => {
  const { data, isLoading } = useQuery(["products"], async () =>
    commerce.products.list()
  );
  useEffect(() => {
    console.debug(data);
  }, [data]);

  function addToCart(id: string) {
    commerce.cart.add(id, 1);
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
        <h1>Start writing your app</h1>
        {isLoading ? (
          <p>loading</p>
        ) : (
          data?.data.map((product, index) => {
            return (
              <div>
                {product && product.image ? (
                  <Image
                    key={`image-${index}`}
                    width={400}
                    height={400}
                    src={product.image.url}
                  />
                ) : null}
                <p key={`product-${index}`}>{product.name}</p>
                <button
                  className="btn"
                  onClick={() => {
                    addToCart(product.id);
                  }}
                >
                  Add to Cart
                </button>
              </div>
            );
          })
        )}
      </main>
    </div>
  );
};

export default Home;
